# Generated by Django 3.2.15 on 2022-08-19 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_about'),
    ]

    operations = [
        migrations.DeleteModel(
            name='About',
        ),
    ]
