# Generated by Django 3.2.15 on 2022-08-25 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_remove_article_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
